/**
    Copyright 2014-2015 Amazon.com, Inc. or its affiliates. All Rights Reserved.
    Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance with the License. A copy of the License is located at
        http://aws.amazon.com/apache2.0/
    or in the "license" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
*/

module.exports = {
  "french press": "You will need an eight cup french press, a grinder, fifty-six grams of whole bean coffee, water at two hundred and five degrees, a wooden stirrer, a scale, a timer, and your favorite mug. To continue, say french press instructions.",
    "french press instructions": "Grind coffee beans into a consistency similar to bread crumbs. <break time =\"10s\" /> Add coffee to the empty carafe, start timer, and pour hot water halfway to the top of the french press. <break time =\"3s\" /> At one minute stir the mixture and fill the carafe to the top with water. <break time =\"10s\" /> Add top to french press. <break time =\"10s\" /> At four minutes press plunger all the way down. <break time =\"3s\" /> Finally, pour coffee into your mug and enjoy!",
  "aeropress": "You will need an aeropress, an aeropress filter, a grinder, seventeen grams of whole bean coffee, water at about two hundred and five degrees, a spoon or paddle, a scale, a timer, and your best mug. To continue, say aeropress instructions",
    "aeropress instructions": "Grind coffee beans into a consistency similar to table salt. <break time=\"10s\" /> Place filter in the aeropress basket, and rinse with hot water to remove paper flavor. <break time=\"5s\" /> Attach the basket to the chamber, place on top of your empty mug, and pour coffee into the chamber. <break time=\"10s\" /> Start timer, and pour water into the chamber up to the number four on the side of the aeropress. Then stir the the mixture. <break time=\"10s\" /> Attach the plunger to the chamber without pressing down to create a pressure seal. <break time=\"10s\" /> At about one minute and thirty seconds, gently press down on the plunger. <break time=\"2s\" /> Remove the aeropress from the mug and Voila! You have a freshly brewed cup of coffee for one.",
  "chemex": "You will need an eight cup chemex, a chemex filter, a grinder, forty-two grams of whole bean coffee, water at about two hundred and five degrees, a spoon, a scale, a timer, and a mug. To continue, say chemex instructions",
    "chemex instructions": "Place filter into chemex so that the single fold is away from the spout. Rinse the filter and pour out the water that collects in the chemex. <break time=\"10s\" /> Grind coffee beans as fine as kosher salt. <break time=\"10s\" /> Pour coffee into chemex filter, place chemex on the scale, and tare the scale balance. <break time=\"10s\" /> Start timer, and pour water into the chemex until the scale reads about one hundred fifty grams. Then stir the mixture. <break time=\"10s\" /> At forty five seconds begin the second pour until the scale reads about four hundred fifty grams. <break time=\"10s\" /> At one minute and forty five seconds begin the third pour until the scale reads about seven hundred grams. <break time=\"10s\" /> At four minutes, pull the filter out, swirl the chemex and serve up a freshly brewed cup of joe!",
  "hariovsixty": "You will need a hario v sixty, a hario v sixty filter, twenty-one grams of whole bean coffee, water at two hundred and five degrees, a scale, a timer, and the mug of your choice. To continue, say hario v sixty instructions",
    "hariovsixtyinstructions": "Grind coffee beans as fine as kosher salt. <break time=\"10s\" /> Fold filter into a cone shape, place inside hario dripper, and rinse with hot water over your mug. <break time=\"10s\" /> Discard of hot water, and pour freshly ground coffee into the brewer. Move the brewer and your mug onto a scale, and tare the balance. Start your timer, pour in just enough water to saturate the grounds, and let bloom for 15 seconds. <break time=\"10s\" /> Slowly add water every ten to fifteen seconds until you reach three hundred and sixty grams. <break time=\"10s\" /> At three minutes remove the dripper, and enjoy your freshly brewed coffee!",
  "clever": "You will need a clever coffee dripper, a number four cone filter, twenty grams of whole bean coffee, water at about two hundred degrees, a scale, a timer, and a decanter. To continue, say clever instructions.",
    "clever instructions": "Grind coffee beans into a consistency similar to bread crumbs. <break time =\"10s\" /> Place filter into the clever brewer and rinse with hot water. <break time =\"10s\" /> Place brewer on the scale, tare the scale to zero, and pour grounds into clever. <break time =\"10s\" /> Start timer and pour water until you reach fifty grams. Coffee should bloom for thirty seconds. <break time =\"10s\" /> Begin the second pour until you have reached four hundred and fifty grams. Wait until the timer reaches two minutes. <break time =\"10s\" /> Place brewer on top of the decanter, and allow the coffee to drain. Coffee will be done within about four minutes. Pour into your favorite mug and enjoy!"
};
